export const INTERCORRENCIA_OPTIONS = [
    "PROBLEMA MECÂNICO",
    "PACIENTE EVADIU",
    "PACIENTE RECUSOU REMOÇÃO",
    "PACIENTE RECUSOU ATENDIMENTO",
    "CANCELADO PELO SOLICITANTE"
];

export const HOSPITALS_SALVADOR = [
  "HOSPITAL GERAL DO ESTADO (HGE)",
  "HOSPITAL GERAL ROBERTO SANTOS",
  "HOSPITAL DO SUBÚRBIO",
  "HOSPITAL SANTO ANTÔNIO (OSID)",
  "UPA BROTAS",
  "UPA BARRIS",
  "UPA SANTO ANTÔNIO",
  "UPA ITAPUÃ",
  "HOSPITAL UNIVERSITÁRIO PROF. EDGARD SANTOS"
];

export const DECISION_OPTIONS = [
    "ENVIAR PARA UNIDADE DE SAÚDE",
    "NÃO ENVIAR PARA UNIDADE DE SAÚDE"
];
